baseURL = "https://nancyngo.netlify.com"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "15"

title = "Nancy Ngo"
[Languages.en]
contentDir = "content/english"
home = "About"
languageCode = "en-us"
languageName = "En"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.main]]
URL = "projects"
name = "Projects"
weight = 4
[params]
author = "Themefisher"
description = "Responsive Multipurpose Parallax HTML5 Template"
googleAnalitycsID = "Your ID"
logo = "images/logo.png"
postShare = true
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/animate-css/animate.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.js]]
URL = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
URL = "plugins/wow/wow.min.js"
[params.preloader]
enable = true
[[params.social_Icon]]
icon = "ti-email"
link = "mailto: nnngo@uwaterloo.ca"
[[params.social_Icon]]
icon = "ti-linkedin"
link = "https://linkedin.com/in/kiminno"
[[params.social_Icon]]
icon = "ti-github"
link = "https://github.com/kiminno"
[[params.social_Icon]]
icon = "ti-folder"
link = "https://devpost.com/Kiminno"

